# Generated by Django 4.0.4 on 2022-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('ALC', 'Alcohol'), ('JCE', 'Juice'), ('SRP', 'Syrup'), ('MLK', 'Lactic'), ('WTR', 'Water'), ('FRT', 'Fruit'), ('VGT', 'Vegetable'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cocktail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cocktails.cocktail'),
        ),
    ]
