# Generated by Django 4.0.4 on 2022-05-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_remove_ingredient_description_ingredient_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
