# Generated by Django 4.0.4 on 2022-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_cocktail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
