# Generated by Django 4.0.4 on 2022-05-27 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('33516d5d-918f-4033-ae7d-c8a34e90eb37'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('category', models.CharField(choices=[('ALC', 'Alcohol'), ('JCE', 'Juice'), ('SRP', 'Syrup'), ('MLK', 'Lactic'), ('WTR', 'Water'), ('FRT', 'Fruit'), ('VGT', 'Vegetable'), ('OTH', 'Other')], default='OTH', max_length=3)),
            ],
        ),
    ]
