# Generated by Django 4.0.4 on 2022-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocktails', '0003_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('category', models.CharField(choices=[('ALC', 'Alcohol'), ('JCE', 'Juice'), ('SRP', 'Syrup'), ('MLK', 'Lactic'), ('WTR', 'Water'), ('FRT', 'Fruit'), ('VGT', 'Vegetable'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('cocktail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cocktails.cocktail')),
            ],
        ),
    ]
