# Generated by Django 4.0.4 on 2022-05-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cocktail',
        ),
    ]
