# Generated by Django 4.0.4 on 2022-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='default.png', upload_to='media/')),
                ('published', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(to='ingredients.ingredient')),
            ],
        ),
    ]
