# Generated by Django 4.0.4 on 2022-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_cocktail_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
