# Generated by Django 4.0.4 on 2022-06-03 21:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_alter_cocktail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
